### PR TITLE
Add a configurable comment message

### PR DESCRIPTION
**Pull request by cco3**
This change uses probot-config to let the deployer customize the body
of the comment that is posted to closed issues.

Additionally, it sets up some tests with jest to test this
functionality.

Dependency: #11 
Issue: #7

### CODE REVIEW

**Comment by cco3** [comment]
Hi @lee-dohm, would you be able to take a look at this PR?

**Comment by cco3** [comment]
Will rebase this on top of master in a bit, thanks!

**Comment by cco3** [comment]
OK, should be ready to go.

**Comment by lee-dohm** [comment]
Thanks for your effort and patience :grinning:

**Pull request merged**
